POST http://localhost:3001/api/posts
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imp1bGVzIiwiaWQiOiI1ZTdjOWE2NjczZTQzNzRhMDA2MDJkODgiLCJpYXQiOjE1ODUyMzEwMDd9.vXdJSW1rq828QMWUQ23uGDx8LSDZNLDq7W5obPuYH88

{
    "title": "dadadada?",
    "author": "me",
    "url": "localhost",
    "likes": 88
}